# 1 Векторы, матрицы, массивы

##  1.1 Создание вектора

In [9]:
import numpy as np
vector_row = np.array([1,2,3])
vector_column = np.array([[1],[2],[3]])
print(vector_column,'\n', vector_row)

[[1]
 [2]
 [3]] 
 [1 2 3]


## 1.2 Создание матрицы

In [10]:
matrix = np.array([[1,2,3],[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

## 1.3 Создание разреженной матрицы

In [12]:
from scipy import sparse
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)
#только не 0 значения

  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (1, 0)	1
  (1, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 1)	5
  (2, 2)	6


## 1.4 Выбор элементов

In [16]:
vector = np.arange(6)

print(matrix[1,1],vector[1])

2 1


## 1.5 Описание матрицы

In [25]:
print(matrix.size, matrix.shape, matrix.ndim) #ndim кол размерностей

9 (3, 3) 2


## 1.6 Применение операций к элементам

In [28]:
add_100 = lambda i: i + 100
vectorized_add_100 = np.vectorize(add_100)
matrix = vectorized_add_100(matrix)
matrix

array([[101, 102, 103],
       [101, 102, 103],
       [104, 105, 106]])

## 1.7 Нахождение максимального и минимального значений

In [32]:
print(f'min {np.min(matrix)}, max {np.max(matrix)}')

min 101, max 106


## 1.8 Среднее значение, дисперсия и стандартное отклонение

In [34]:
print(f'Среднее {np.mean(matrix)}, Дисперсия {np.var(matrix)}, Стандартное отклонение {np.std(matrix)}')

Среднее 103.0, Дисперсия 2.6666666666666665, Стандартное отклонение 1.632993161855452


## 1.9 Реформирование массивов

In [36]:
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1.10 Транспонирование 

In [38]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 1.11 Сглаживание матрицы

In [41]:
matrix.flatten() # Преобразование в одномерный массив

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.12 Нахождение ранга матрицы

In [43]:
np.linalg.matrix_rank(matrix)

2

## 1.13 Вычисление определителя матрицы

In [47]:
np.linalg.det(matrix)

0.0

## 1.14 Получение диагонали матрицы

In [55]:
matrix.diagonal(offset=0) #+1 выше на 1 диагонали 

array([1, 5, 9])

## 1.15 Вычисление следа матрицы

In [51]:
matrix.trace() # Сумма элементов на диагонали

15

## 1.16 Нахождение собственных значений и собственных векторов

In [57]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(f'Собственные значения :{eigenvalues}, Соственные вектора  : {eigenvectors}')

Собственные значения :[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15], Соственные вектора  : [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## 1.17 Вычисление скалярных произведений

In [59]:
vector_a = np.arange(3)
vector_b = np.arange(4, 7)
np.dot(vector_a,vector_b)

17

In [60]:
vector_a @ vector_b

17

## 1.18 Сложение и вычитание матриц

In [73]:
matrix_b = np.arange(11, 20).reshape(3,3)
print(np.add(matrix_b, matrix), '\n\n', np.subtract(matrix_b, matrix))

[[12 14 16]
 [18 20 22]
 [24 26 28]] 

 [[10 10 10]
 [10 10 10]
 [10 10 10]]


## 1.19 Умножение матриц

In [76]:
np.dot(matrix, matrix_b) # * для поэлементного и заменя dot:@

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

## 1.20 Обращение матрицы

In [80]:
matr = np.array([[1,7],[4,3]])
np.linalg.inv(matr) # AA^-1=I

array([[-0.12,  0.28],
       [ 0.16, -0.04]])

## 1.21 Генерирование случайных значений

In [87]:
np.random.seed(42)
np.random.random(3) # array([0.37454012, 0.95071431, 0.73199394])
np.random.randint(0, 10, 3) 

array([4, 6, 9])